# This workflow will run unit tests

name: Run Unit Tests
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-timeout pytest-cov

      - name: Test Github Branch Parsing
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_github_branch_parsing.py

      - name: Test Github Utils
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_github_utils.py

      - name: Test License Parsing
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_licenses.py

      - name: Test Skill Entry
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_skill_entry.py

      - name: Test Utils
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_utils.py

      - name: Test Search Skill
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_search_skill.py

      - name: Test OSM
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pytest tests/test_osm.py
